SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

SET NAMES utf8mb4;

INSERT IGNORE INTO `topics` (`topic_id`, `created_at`, `description`, `title`, `updated_at`) VALUES
    (1,	NOW(),	'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquet nibh praesent tristique magna sit amet purus. Sagittis orci a scelerisque purus semper eget duis at tellus. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Interdum varius sit amet mattis vulputate enim nulla aliquet. Tristique risus nec feugiat in fermentum posuere urna nec tincidunt. Leo a diam sollicitudin tempor. Rhoncus est pellentesque elit ullamcorper. Laoreet id donec ultrices tincidunt. Aliquet lectus proin nibh nisl. Elementum nibh tellus molestie nunc non blandit. Senectus et netus et malesuada fames ac turpis egestas. Sollicitudin tempor id eu nisl nunc. Felis donec et odio pellentesque diam volutpat commodo sed. Sed cras ornare arcu dui vivamus arcu felis bibendum ut. Adipiscing at in tellus integer. Egestas tellus rutrum tellus pellentesque. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor. Tortor posuere ac ut consequat semper viverra.',	'Angular',	NOW()),
    (2,	NOW(),	'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquet nibh praesent tristique magna sit amet purus. Sagittis orci a scelerisque purus semper eget duis at tellus. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Interdum varius sit amet mattis vulputate enim nulla aliquet. Tristique risus nec feugiat in fermentum posuere urna nec tincidunt. Leo a diam sollicitudin tempor. Rhoncus est pellentesque elit ullamcorper. Laoreet id donec ultrices tincidunt. Aliquet lectus proin nibh nisl. Elementum nibh tellus molestie nunc non blandit. Senectus et netus et malesuada fames ac turpis egestas. Sollicitudin tempor id eu nisl nunc. Felis donec et odio pellentesque diam volutpat commodo sed. Sed cras ornare arcu dui vivamus arcu felis bibendum ut. Adipiscing at in tellus integer. Egestas tellus rutrum tellus pellentesque. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor. Tortor posuere ac ut consequat semper viverra.',	'Java',	NOW());